masks/masks/facemask/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views
 
urlpatterns = [
  path('', views.home,name="home"),
  path('sucess/',views.success,name="sucess"),
  path('buscar/',views.buscar,name="buscar"),
  path('data/',views.userdata,name="data"),
  path('soporte/',views.support,name="support"),
  path('sent/',views.successcomment,name="sent"),
  path('sports/',views.ViewMasksSport.as_view(),name="sports"),
  path('kids/',views.ViewMasksKids.as_view(),name="kids"),
  path('casual/',views.ViewMasksCasual.as_view(),name="casual"),
  path('different/',views.ViewMasksRar.as_view(),name="different"),
  path('user/',views.UserBoard.as_view(),name='userboard'),
  url('login/', LoginView.as_view(), name= 'login'),
  url('logout/', LogoutView.as_view(), name= 'logout'),
  url('create/', views.CreateMask, name= 'create'),
  url('signup/',views.signup, name='signup'),
]

masks/masks/masks/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
    path("", include("facemask.urls")),
    
]

masks/masks/facemask/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class SupportModel(models.Model):
    usuario = models.CharField(max_length=30)
    asunto = models.CharField(max_length=100)
    comment = models.TextField()

class MaskCreator(models.Model):
    # telas
    ALG = "Algodón"
    POL = "Poliéster"
    FRA = "Franela"
    SBN = "Sábana"
    FABR_CHOICES = [(ALG,"Algodón"),(POL,"Poliéster"),(FRA,"Franela"),(SBN,"Sábana")]
    # colores
    AZU = "Azul"
    NEG = "Negro"
    ROJ = "Rojo"
    BLA = "Blanco"
    GRI = "Gris"
    ROS = "Rosa"
    CAF = "Cafe"
    COL_CHOICES = [(AZU,"Azul"),(NEG,"Negro"),(ROJ,"Rojo"),
                (BLA,"Blanco"),(GRI,"Gris"),(ROS,"Rosa"),(CAF,"Cafe")]
    usuario = models.CharField(max_length=30)
    tela = models.CharField(max_length=20,choices=FABR_CHOICES)
    color = models.CharField(max_length=20,choices=COL_CHOICES,default=BLA)
    capas = models.IntegerField(default=2,validators=[MinValueValidator(1),MaxValueValidator(4)])

class BrandMasks(models.Model):
    INF = "Infantil"
    SPT = "Deportes"
    CAS = "Casual"
    RAR = "Raro"
    TYPE_CHOICES = [
    (INF, "Infantil"), (SPT,"Deportes"),
     (CAS,"Casual"), (RAR, "Raro")]
    marca = models.CharField(max_length=50)
    enlace = models.CharField(max_length=300)
    photo = models.CharField(max_length=300)
    category = models.CharField(max_length=15,choices=TYPE_CHOICES)
    price = models.FloatField(default=5.0,validators=[
            MaxValueValidator(500),
            MinValueValidator(5.0)
    ])

masks/masks/facemask/forms.py
from django import forms
from .models import MaskCreator, SupportModel
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class MaskCreatorForm(forms.ModelForm):
  class Meta:
    model = MaskCreator
    fields = ('usuario','tela','color','capas')

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class SupportForm(forms.ModelForm):
  #  comment = forms.CharField(widget=forms.Textarea(attrs={'cols':80, 'rows': 20}))
    class Meta:
        model = SupportModel
        fields = "__all__"
        labels = {"asunto":"Asunto", "comment":"Comentario"}
        widgets = {
            'comment': forms.Textarea(attrs={'cols': 80, 'rows': 10,'style':'resize:none;'}),
            'asunto' : forms.Textarea(attrs={'cols': 80, 'rows': 1,'style':'resize:none;'}),
        }

masks/masks/facemask/views.py
from django.http import request
from django.shortcuts import redirect, render
from django.views.generic import ListView
from .forms import MaskCreatorForm, SignUpForm, SupportForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import BrandMasks, MaskCreator, SupportModel
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy

# Create your views here.
def home(request):
  return render(request, "home.html")

def login(request):
  return render(request, "registration/login.html")

def success(request):
  return render(request,"success.html")

def successcomment(request):
  return render(request,'successcomment.html')

def userdata(request):
  return render(request,"datos.html")

def support(request):
    if request.method=='POST':
        form = SupportForm(request.POST)
        print("here?")
        print(form.is_valid())
        if form.is_valid():
            form.save()
            return redirect('sent')
    else:
        initial = {'usuario':request.user.username}
        form = SupportForm(initial=initial)

    return render(request, 'soporte.html', {'form': form})

class UserBoard(ListView):
    model = MaskCreator
    template_name = "userboard.html"

class ViewMasksSport(ListView):
    model = BrandMasks
    template_name = "sport.html"

class ViewMasksKids(ListView):
    model = BrandMasks
    template_name = "kids.html"

class ViewMasksCasual(ListView):
    model = BrandMasks
    template_name = "casual.html"

class ViewMasksRar(ListView):
    model = BrandMasks
    template_name = "different.html"

def CreateMask(request):
    if request.method=='POST':
        form = MaskCreatorForm(request.POST)
        print("here?")
        print(form.is_valid())
        if form.is_valid():
            form.save()
            return redirect('userboard')
    else:
        initial = {'usuario':request.user.username}
        form = MaskCreatorForm(initial=initial)

    return render(request, 'create.html', {'form': form})

def buscar(request):
  if request.method == "POST":
    searched = request.POST['searched']
    mask_id = BrandMasks.objects.filter(marca__icontains=searched)
    return render(request,'search.html',{'searched':searched,'brandmasks':mask_id})
  else:
    return render(request,'not_found.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('sucess')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

masks/masks/facemask/templates/base.html
<!DOCTYPE html>
<!-- Fuente del logo: https://fonts.google.com/specimen/Lobster -->
<head>
    {% load bootstrap4 %}
 
	  {# CSS Bootstrap #}
	  {% bootstrap_css %}
        {% block head %}
        
        {% endblock %}
      
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="#">
            <img src="/static/facemask/logo.svg" width="40" height="28" alt="">
        </a>
        <a class="navbar-brand" href="#" id="brandname">MaSktyle</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Inicio <span class="sr-only">(current)</span></a>
            </li>
    
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categorías
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'sports' %}">Deportes</a>
                <a class="dropdown-item" href="{% url 'casual' %}">Casual</a>
                <a class="dropdown-item" href="{% url 'different' %}">Raro</a>
                <a class="dropdown-item" href="{% url 'kids' %}">Infantil</a>
              </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create' %}">Crea el tuyo </a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#"> </a>
            </li>

          <form class="form-inline text-right" action="{% url 'buscar' %}" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="searched">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="visibility: hidden;">Search</button>
          </form>
        </ul>
          <ul class="navbar-nav ">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userboard' %}">¡Hola {{ user.username }}!</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}" style="color: blueviolet;">Log Out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
            </li>
          {% endif %}
  
          </ul>
        </div>
      </nav>
<div class="container" >
  {% block content %}
  {% endblock %}
</div>
</div>
<!-- Footer -->
<footer class="page-footer font-small teal pt-4" style="background-color: rgb(201, 197, 197); margin-top: 50px;">

    <!-- Footer Text -->
    <div class="container-fluid text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">
  
          <!-- Content -->
          <h5 class="text-uppercase font-weight-bold">Acerca de</h5>
          <p>El sitio fue elaborado con fines de facilitar la búsqueda de un cubrebocas ideal para cada persona,
              hoy en día es fundamental su uso.
          </p>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none pb-3">
  
        <!-- Grid column -->
        <div class="col-md-6 mb-md-0 mb-3">
  
          <!-- Content -->
          <h5 class="text-uppercase font-weight-bold">¡Contáctanos!</h5>
          <p>Ciudad de México, Gustavo A. Madero. Tel: +52 5522910000</p>
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Text -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3" style="background-color: black; color: white;">© 2021 Copyright:
      <a style="color:white;" href="#"> maskswithlove.com</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->
  {# JS y jQuery Bootstrap #}
	  {% bootstrap_javascript jquery='full' %}
</body>

masks/masks/facemask/templates/casual.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}

    <div class="row" style="margin-top: 80px;">
    </div>
    <h2 class="display-5 text-center" id="brandname" style="margin-bottom: 30px;">Casual/cotidiano</h2>

    <div class="row" style="margin-top:15px">
      {% for brandmasks in brandmasks_list %}
      {% if brandmasks.category == "Casual" %}
          <div class="col-3">
              <div class="card border-0" style="width: 16rem;">
                  <img height="205px" width="250px" class="card-img-top" src=" {{ brandmasks.photo }} " alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">{{ brandmasks.marca }}</h5>
                    <p class="card-text">Precio: ${{ brandmasks.price }}</p>
                    <p class="card-text">Categoría: {{ brandmasks.category }}</p>
                  </div>
                  
                  <div class="card-body">
                    <a href="{{ brandmasks.enlace }}" class="card-link" style="color:rgb(240, 21, 21);">Ver más detalles y comprar</a>
                  </div>
              </div>
          </div>
      {% endif %}
      {% endfor %}
  </div>
{% endblock %}

masks/masks/facemask/templates/create.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}
    <div class="row row-margin-05" style="margin-bottom: 30px;"></div>
    {% if user.is_authenticated %}
        <h2 class="display-5 text-center" id="brandname" style="margin-top: 90px;">Creación de mascarilla propia</h2>
        <form class="form" method="POST" style="margin-top: 35px; margin-bottom: 60px;">
            {% csrf_token %}
            {% for field in form %}
                {% if field.label != "Usuario" %}
                <div class="row" style="margin-bottom: 15px;"> 
                    <div class="col-4">
                    <h5 id="brandname">{{ field.label_tag }}</h5>
                        {% if field.help_text %}
                        <sup>{{ field.help_text }}</sup>
                        {% endif %}
                    {{ field.errors }}
                    </div>
                    <div class="col-4">
                    {{ field }}
                    </div>
                {% else %}
                <div class="form-group" style="visibility: hidden;"> 
                    {{ field.label_tag }}
                        {% if field.help_text %}
                        <sup>{{ field.help_text }}</sup>
                        {% endif %}
                    {{ field.errors }}
                    {{ field }}
                {% endif %}
            </div>
            {% endfor %}
            <input class="btn btn-secondary" type="submit" value="Submit">
        </form>

    {% else %}
        <div class="row row-margin-05" style="margin-top: 90px;">
        <h6 class="display-6 text-center">Lo sentimos</h6>
    </div>
        <div class="row row-margin-05" style="margin-top: 10px;">
        <h6 class="display-6 text-center">Primero debes iniciar sesión</h6>
        </div> 
    {% endif %}
    <div class="row row-margin-05" style="margin-bottom: 60px;"></div>

{% endblock %}

masks/masks/facemask/templates/datos.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}
    <div class="row row-margin-05" style="margin-bottom: 30px; margin-top: 45px;"></div>
    <div class="row row-margin-05">
        <div class="col-12">
        <h3 class="card-title mb-4 mt-1" id="brandname" style="margin-top: 30px;">Bienvenido, {{ user.first_name }}</h3>
        <h5>Datos de usuario</h5>
        </div>
    </div>
<!-- botones que complementan el "dashboard" del usuario logeado -->
    <div class="row row-margin-05" style="margin-top: 20px;">
        <div class="col-4">
            <a href="{% url 'userboard' %}"><button type="button" class="btn btn-dark btn-block">Mis creaciones</button></a>
        </div>
        <div class="col-4">
            <a href="{% url 'data' %}"><button type="button" class="btn btn-outline-dark btn-block" >Mis datos</button></a>
        </div>
        <div class="col-4">
            <a href="{% url 'support' %}"><button type="button" class="btn btn-dark btn-block">Soporte</button></a>
        </div>
    </div>
<!-- seccion de datos de usuario -->
    <div class="row row-margin-05" style="margin-top: 30px;">
        <div class="col-1">
            <h5 id="brandname">Usuario: </h5>
        </div>
        <div class="col-1">
            <h5>{{ user.username }}</h5>
        </div>
    </div>
    <div class="row row-margin-05" style="margin-top: 30px;">
        <div class="col-1">
            <h5 id="brandname">Nombre: </h5>
        </div>
        <div class="col-1">
            <h5>{{ user.first_name }}</h5>
        </div>
    </div>
    <div class="row row-margin-05" style="margin-top: 30px;">
        <div class="col-1">
            <h5 id="brandname">Apellido(s): </h5>
        </div>
        <div class="col-1">
            <h5>{{ user.last_name }}</h5>
        </div>
    </div>
    <div class="row row-margin-05" style="margin-top: 30px;">
        <div class="col-1">
            <h5 id="brandname">Email: </h5>
        </div>
        <div class="col-1">
            <h5>{{ user.email }}</h5>
        </div>
    </div>
    <div class="row row-margin-05" style="margin-bottom: 60px;"></div>

{% endblock %}

masks/masks/facemask/templates/different.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}

    <div class="row" style="margin-top: 80px;">
    </div>
    <h2 class="display-5 text-center" id="brandname" style="margin-bottom: 30px;">Estilo diferente</h2>
    <div class="row" style="margin-top:15px">
    {% for brandmasks in brandmasks_list %}
    {% if brandmasks.category == "Raro" %}

        <div class="col-3">
            <div class="card border-0" style="width: 16rem;">
                <img height="205px" width="250px" class="card-img-top" src=" {{ brandmasks.photo }} " alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{ brandmasks.marca }}</h5>
                  <p class="card-text">Precio: ${{ brandmasks.price }}</p>
                  <p class="card-text">Categoría: {{ brandmasks.category }}</p>
                </div>
                
                <div class="card-body">
                  <a href="{{ brandmasks.enlace }}" class="card-link" style="color:rgb(240, 21, 21);">Ver más detalles y comprar</a>
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}

{% endblock %}

masks/masks/facemask/templates/kids.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}

    <div class="row" style="margin-top: 80px;">
    </div>
    <h2 class="display-5 text-center" id="brandname" style="margin-bottom: 30px;">Infantil</h2>

    <div class="row" style="margin-top:15px">
      {% for brandmasks in brandmasks_list %}
      {% if brandmasks.category == "Infantil" %}
          <div class="col-3">
              <div class="card border-0" style="width: 16rem;">
                  <img height="205px" width="250px" class="card-img-top" src=" {{ brandmasks.photo }} " alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">{{ brandmasks.marca }}</h5>
                    <p class="card-text">Precio: ${{ brandmasks.price }}</p>
                    <p class="card-text">Categoría: {{ brandmasks.category }}</p>
                  </div>
                  
                  <div class="card-body">
                    <a href="{{ brandmasks.enlace }}" class="card-link" style="color:rgb(240, 21, 21);">Ver más detalles y comprar</a>
                  </div>
              </div>
          </div>
      {% endif %}
      {% endfor %}
  </div>
{% endblock %}

masks/masks/facemask/templates/search.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}
    <div class="row row-margin-05" style="margin-bottom: 80px;"></div>
    {% if searched %}
    <h1 id="brandname" >Busqueda de: </h1> <h3> {{ searched }} </h3>
    <br/>
    {% for brandmask in brandmasks %}
        {% if forloop.first %}<div class="row" style="margin-top:15px">{% endif %}
            <div class="col-3">
                <div class="card border-0" style="width: 16rem;">
                    <img height="205px" width="250px" class="card-img-top" src=" {{ brandmask.photo }} " alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title">{{ brandmask.marca }}</h5>
                    <p class="card-text">Precio: ${{ brandmask.price }}</p>
                    <p class="card-text">Categoría: {{ brandmask.category }}</p>
                    </div>
                    
                    <div class="card-body">
                    <a href="{{ brandmask.enlace }}" class="card-link" style="color:rgb(240, 21, 21);">Ver más detalles y comprar</a>
                    </div>
                </div>
            </div>
        
        {% if forloop.last %}</div>{% endif %}
    {% endfor%}
    {% else %}
        <h1>No ingresó búsqueda</h1>
    {% endif %}
    
    <div class="row row-margin-05" style="margin-bottom: 60px;"></div>

{% endblock %}

masks/masks/facemask/templates/sport.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}

    <div class="row" style="margin-top: 80px;">
    </div>
    <h2 class="display-5 text-center" id="brandname" style="margin-bottom: 30px;">Deportes</h2>
    <div class="row" style="margin-top:15px">
    {% for brandmasks in brandmasks_list %}
    {% if brandmasks.category == "Deportes" %}
        <div class="col-3">
            <div class="card border-0" style="width: 16rem;">
                <img height="205px" width="250px" class="card-img-top" src=" {{ brandmasks.photo }} " alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{ brandmasks.marca }}</h5>
                  <p class="card-text">Precio: ${{ brandmasks.price }}</p>
                  <p class="card-text">Categoría: {{ brandmasks.category }}</p>
                </div>
                
                <div class="card-body">
                  <a href="{{ brandmasks.enlace }}" class="card-link" style="color:rgb(240, 21, 21);">Ver más detalles y comprar</a>
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

masks/masks/facemask/templates/success.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}
    <div class="row row-margin-05" style="margin-bottom: 80px;"></div>

    <div class="row row-margin-05" style="margin-bottom: 30px;">
        <h3 style="margin-top: 30px;">¡Te has registrado con éxito, ahora inicia sesión!</h3>
    </div>
    <div class="row row-margin-05" style="margin-top: 20px;">
        <a style="color:white;" href="{% url 'login' %}"><button class="btn btn-primary btn-block">Iniciar sesión</button></a>
    </div>

    <div class="row row-margin-05" style="margin-bottom: 60px;"></div>

{% endblock %}

masks/masks/facemask/templates/userboard.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'facemask/style.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata">

{% endblock %}
{% block content %}
    <div class="row row-margin-05" style="margin-bottom: 30px; margin-top: 45px;"></div>
    <div class="row row-margin-05">
        <div class="col-12">
        <h3 class="card-title mb-4 mt-1" id="brandname" style="margin-top: 30px;">Bienvenido, {{ user.first_name }}</h3>
        <h5>Aquí podrás visualizar tus creaciones.</h5>
        </div>
    </div>
<!-- botones que complementan el "dashboard" del usuario logeado -->
    <div class="row row-margin-05" style="margin-top: 20px;">
        <div class="col-4">
            <a href="{% url 'userboard' %}"><button type="button" class="btn btn-outline-dark btn-block">Mis creaciones</button></a>
        </div>
        <div class="col-4">
            <a href="{% url 'data' %}"><button type="button" class="btn btn-dark btn-block">Mis datos</button></a>
        </div>
        <div class="col-4">
            <a href="{% url 'support' %}"><button type="button" class="btn btn-dark btn-block">Soporte</button></a>
        </div>
    </div>

<!-- sección de creaciones -->
    <div class="row row-margin-05" style="margin-top: 40px;">
        {% for maskcreator in maskcreator_list %}
            {% if maskcreator.usuario == user.username %}
            {% if forloop.first %}<div class="row" style="margin-top:15px">{% endif %}
                <div class="col-3">
                    <div class="card border-0" style="width: 16rem;">
                        <img height="205px" width="250px" class="card-img-top" src="/static/facemask/{{ maskcreator.color }}.jpg " alt="Card image cap">
                        <div class="card-body">
                        <h5 class="card-title">Id: {{ maskcreator.id }}</h5>
                        <p class="card-text">Color: {{ maskcreator.color }}</p>
                        <p class="card-text">Tipo de tela: {{ maskcreator.tela }}</p>
                        <p class="card-text">Cantidad de capas: {{ maskcreator.capas }}</p>
                        </div>
                    
                    </div>
                </div>
            {% if forloop.counter|divisibleby:5 or forloop.counter|divisibleby:9 %}</div><div class="row">{% endif %}
            {% if forloop.last %}</div>{% endif %}
            {% endif %}
        {% endfor %}
    </div>
    <div class="row row-margin-05" style="margin-bottom: 60px;"></div>

{% endblock %}